- apps/orgs/actions.py
We are calling this function inside of a exception, that is why this also needed to be in try catch block
> Generate Not Found Item Error when managed user id is not found

- apps/travelperk/helpers.py
- apps/travelperk/views.py
> add travelperk custom purpose using description structure from advanced settings

- apps/integrations/serializers.py
- tests/test_integrations/test_views.py
https://app.clickup.com/t/86cwtmh36
> fix: support marking an integration back as active

- apps/integrations/serializers.py
https://app.clickup.com/t/86cwtmh36
> fix: support marking an integration back as active (update / create bug)

- scripts/sql/004-show-bc-for-all-orgs.sql
https://app.clickup.com/t/86cx5t0we
> fix: show dynamics in landing page for all orgs

- tests/fixture.py
Clickup: 
https://app.clickup.com/t/86cxnedtq
> fix: redact S3 URL in test data

- .gitignore
- deploy_dump.sh
- requirements.txt
> chore: remove unused package

- admin_settings/sentry.py
- apps/fyle_hrms_mappings/apps.py
- apps/integrations/apps.py
- apps/orgs/apps.py
- apps/users/apps.py
- requirements.txt
fix: lib dependencies
https://app.clickup.com/
> fix: Upgrade dependencies

- apps/users/helpers.py
fix: get access token
https://app.clickup.com/
> fix: access token

- scripts/python/backfill_integrations_records.py
https://app.clickup.com/t/86cxhfhnx
> feat: add script to backfill integration records for BambooHR and TravelPerk

- apps/integrations/views.py
- scripts/python/backfill_integrations_records.py
https://app.clickup.com/t/86cxhfhdp
> feat: add PATCH support to partially update integration records

- apps/integrations/views.py
- apps/travelperk/actions.py
- apps/travelperk/views.py
- scripts/python/backfill_integrations_records.py
- tests/test_travelperk/test_views.py
https://app.clickup.com/t/86cxhffaj
> feat: deactivate integration on TravelPerk disconnect

- apps/bamboohr/tasks.py
- apps/bamboohr/views.py
- apps/integrations/views.py
- apps/travelperk/actions.py
- apps/travelperk/views.py
- scripts/python/backfill_integrations_records.py
- tests/test_bamboohr/test_views.py
- tests/test_travelperk/test_views.py
https://app.clickup.com/t/86cxv5q9k
> feat: deactivate integration on BambooHR disconnect

- apps/bamboohr/tasks.py
- apps/bamboohr/views.py
- apps/integrations/views.py
- apps/travelperk/actions.py
- apps/travelperk/views.py
- scripts/python/backfill_integrations_records.py
- tests/test_bamboohr/fixtures.py
- tests/test_bamboohr/test_views.py
- tests/test_travelperk/test_views.py
- add a BambooHR record to the integrations table on connection
- return 400 on invalid login attempts
https://app.clickup.com/t/86cxhffbe
> feat: add a BambooHR record to the integrations table on connection

- apps/bamboohr/tasks.py
- apps/bamboohr/views.py
- apps/integrations/views.py
- apps/travelperk/actions.py
- apps/travelperk/serializers.py
- apps/travelperk/views.py
- scripts/python/backfill_integrations_records.py
- tests/test_bamboohr/fixtures.py
- tests/test_bamboohr/test_views.py
- tests/test_travelperk/test_views.py
https://app.clickup.com/t/86cxhffaj
> feat: add a travelperk record to the integrations table on connection

- apps/bamboohr/tasks.py
- apps/bamboohr/views.py
- apps/integrations/views.py
- apps/travelperk/actions.py
- apps/travelperk/serializers.py
- apps/travelperk/views.py
- scripts/python/backfill_integrations_records.py
- tests/test_bamboohr/fixtures.py
- tests/test_bamboohr/test_views.py
- tests/test_travelperk/fixtures.py
- tests/test_travelperk/test_views.py
https://app.clickup.com/t/86cxhfkgp
> test: bambooHR and travelperk - POST to integrations on connection

- apps/bamboohr/tasks.py
- apps/bamboohr/views.py
- apps/integrations/views.py
- apps/travelperk/actions.py
- apps/travelperk/serializers.py
- apps/travelperk/views.py
- scripts/python/backfill_integrations_records.py
- tests/test_bamboohr/fixtures.py
- tests/test_bamboohr/test_views.py
- tests/test_integrations/fixture.py
- tests/test_integrations/test_views.py
- tests/test_travelperk/fixtures.py
- tests/test_travelperk/test_views.py
https://app.clickup.com/t/86cxhfkgp
> test: POST and PATCH `/integrations/`

- .github/workflows/hulk_deployment.yaml
https://app.clickup.com/1864988/v/l/li/901605343641
> Feat: Add submodule recursive to hulk

- apps/integrations/views.py
- tests/test_integrations/test_views.py
https://app.clickup.com/t/86cxhfm6w
> test: fix patch tests

- .github/workflows/staging_deployment.yml
> chore: deploy to all staging envs

- .github/workflows/qa_deployment.yml
> chore: remove qa deploy

- apps/bamboohr/tasks.py
- apps/travelperk/actions.py
- scripts/python/backfill_integrations_records.py
> refactor: fix comments

- admin_settings/sentry.py
fix: pii
https://app.clickup.com/t/86cxygv7h
> fix: Sentry pii

- apps/bamboohr/views.py
- apps/travelperk/views.py
https://app.clickup.com/t/86cxxmf7d
> fix: update integration object on bamboohr/travelperk token expiry

- requirements.txt
fix: medium vulnerabilities
https://app.clickup.com/
> fix: Medium vulnerabilities

- apps/integrations/views.py
- tests/test_integrations/test_views.py
> fix: order by type and then updated for integrations/

- scripts/python/backfill_integrations_records.py
https://app.clickup.com/t/86cxv5q9k
https://app.clickup.com/t/86cxv5qa0
> fix: correct fields in backfill scripts and format output

- requirements.txt
https://app.clickup.com/1864988/v/l/6-901605343641-1
> Feat: Remove requirements that depends on pgevents

- apps/travelperk/views.py
> fix: Travelperk token revoke

- apps/integrations/views.py
- tests/test_integrations/test_views.py
> fix: multi org sandbox patches to integrations/

- Dockerfile
- health_check.sh
app.clickup.com/1864988/v/l/li/901605343641
> Feat: Add health check

- apps/bamboohr/tasks.py
- apps/bamboohr/views.py
> fix: BambooHR API token health check and expiry logic

- Dockerfile
- docker-compose-pipeline.yml
> fix: Run container with non root user

- apps/bamboohr/tasks.py
- apps/bamboohr/views.py
- apps/fyle_hrms_mappings/models.py
- apps/travelperk/views.py
https://app.clickup.com/1864988/v/l/li/901605343641
> Feat: Add updated_at to update and bulk_update

- apps/internal/migrations/0001_auto_generated_sql.py
https://app.clickup.com/1864988/v/l/li/901605343641
> Feat: Add replication related queries

- Dockerfile
> fix: update setuptools, wheel

- apps/orgs/actions.py
- apps/orgs/utils.py
- apps/travelperk/actions.py
- apps/travelperk/helpers.py
- apps/travelperk/views.py
- apps/users/helpers.py
- apps/users/views.py
- requirements.txt
- tests/conftest.py
- tests/test_orgs/test_views.py
- tests/test_travelperk/test_actions.py
- tests/test_travelperk/test_views.py
feat: Move to v1 from v1beta
https://app.clickup.com/
> feat: Move to v1

- tests/conftest.py
- tests/fixture.py
- tests/test_bamboohr/mock_setup.py
- tests/test_bamboohr/test_email.py
- tests/test_bamboohr/test_tasks.py
- tests/test_bamboohr/test_views.py
- tests/test_bamboosdk/test_employee.py
- tests/test_fyle_employee_imports/fixtures.py
- tests/test_fyle_employee_imports/mock_setup.py
- tests/test_fyle_employee_imports/test_bamboo_hr.py
- tests/test_fyle_employee_imports/test_base.py
- tests/test_travelperk/mock_setup.py
- tests/test_travelperk/test_actions.py
- tests/test_travelperk/test_connector.py
- tests/test_travelperk/test_helpers.py
- tests/test_users/mock_setup.py
- tests/test_users/test_helpers.py
> Feat: Resolve overall test comments 

- tests/conftest.py
- tests/fixture.py
- tests/test_bamboohr/mock_setup.py
- tests/test_bamboohr/test_email.py
- tests/test_bamboohr/test_tasks.py
- tests/test_bamboohr/test_views.py
- tests/test_bamboosdk/test_employee.py
- tests/test_fyle_employee_imports/fixtures.py
- tests/test_fyle_employee_imports/mock_setup.py
- tests/test_fyle_employee_imports/test_bamboo_hr.py
- tests/test_fyle_employee_imports/test_base.py
- tests/test_travelperk/mock_setup.py
- tests/test_travelperk/test_actions.py
- tests/test_travelperk/test_connector.py
- tests/test_travelperk/test_helpers.py
- tests/test_users/fixtures.py
- tests/test_users/mock_setup.py
- tests/test_users/test_helpers.py
> Feat: Added test suite for users app

- apps/integrations/views.py
> fix: hide sage export api
